language: node_js
node_js:
- '0.12'
addons:
  sauce_connect: true
env:
  global:
#You don't need the WITH_DOCS variable (this is only for me to launch the e2e tests of the generated doc internally)
  - WITH_DOCS=true
  - secure: lVqaKzskSfk4RQRYWhb/9eF9iY/18+ZDD3+85tCZVQP/SNRybvAUm9TgCJP8T1JYU4xjmKeXsglg6XHabjbTOqHDo76vKk47rtFD8MOz5/GjGaC0fPNbHgjrXcinMquv1P1tJRle31kLf+BBtrj1LAl/PgoGTTm63OhXDiO6ijVoIVgSLHXWHJVSDu2FsEgAn+rO0nQkMUHgAHs1V1ocy+kZjRf+rIMSn7K6Va/sY0dN7r/efB3yQCBDxCKarORCU+ixDtwEApplWr+8p/IXsb4P3NQ80dmIBzYOd++cAVe1GfmMYcqBgZMg7+EjY14RoL+XwPimu7fQ2GhhQbzFrvJYb73a/CSfaMbtvO2oCCLAbfiPuijt7DhuuWJbhtKHTaJ+HHiEExVk6DA9VrQz1dIBgFD8FtblRskxkTRFsIyQGxdqnpoU/gCNL2MoluBtYTMai6TrcDNxZ+U1zlCTGyWbHr8hy/WUW7nW48KS2LlHbNjBlCw6G+WKy2IotyMOahqS+Fnksk0/QeHNAjUYy8lIpG/hZvdalJW8GsMszyeOrw3Pt6pXkjf7U74oLTmimhkHB8WjjV/FtXS70VG0aI3ALRJLSVJlGj1t0NCYI5Lf6CpkpwK0f7/OTs6R5WVpxuo9f4rhJngNPkyEj8HWp2wquihuS1VAvxtvHOPZOd4=
  - secure: fVv0ZWvXcF83t7nLsBYKaXqwMQ3UXlXh/kQ+IHSVifsGlHFZ5bVVghKirpGli1XlvpymGJAhCup3ZdpSeeMMXw4DvjIyAo5LCdElqpYR69w1bW4Bplx1/usYwaRq266i1srlYaXq3mDMg1CBfZ55co7b7PACvDS2IHaq8SY7rAcO3G4C6wHLgbcfB2+TVsIplAz6ntj/2PoqQv60Slsyg0K+8CMaBs/d7f4ckaCUww2TNGyArm1Qiam5+3fvmk+BrJHwX8B3jZwXguh+MaWGi/7Kb2nocT62HijDI0BcZCTjwLcEomZI68ha4T9qjiFOYkrks+fPQZHa8aLfr+LbOW7eSaBf9+ljEoKTx/Gq/NTOoXhvcT2JgJ+nF22RStxN2mehZi/FKHw3IkrNPqpyRsIkNC2seAuAkUHzwJfEuhPq/nraDePi1o3E58c8YYC7SVi+uZGrLG0md1SlQl0iITK16yZYHS/yJAIwGMzrcatQH/2r/WmYCiVox/OZCOhL/vX1CKAXn+b1KlEoesMHuwewq0cPFs94brUQIdDCltRzqCjxzSjKM6z3zKg5cu+8AAglm62RQkD2HdTJIzT/Kf6HLVn0zgGRCoF7f7uAkLO0j4efYgbMnyIUYSWfn8Gr6Xo53tgNzjVdpFmXQ0p6Vpmj/KqHJ1bxC13Wd8l6vS0=
  - secure: rLqLeX4/4gYjXPFmLiAdcy8l2v9WbBvq5EajLtFNkUaAxrqlgZQtwNXdGNrzW7ZI7R86eoknVX9WMRNGQhXOafTNXJ70i3SMtcaQCVvsmwOS+Tz67MTnsLs4tHEivTe5TflU1VpeeF3cZE7/c3H7XxbHDjo7gZR/3C/THBobHjEOk/wuClA97YN9cGwgnc9krki96n/o7MCeDfptsfUNacdGgl77ZLl+2xWzspr2CwYpltPVCT9nmKesLc7cLd5nVw4FVCcTeRV0cXaoQ4ZDfqz3fZIFc3FcNwXbdVqO9E4u8pW68MD/uUGmJXNGDGmLmx8Pwd/fx6cjlIUHOqZYWd8mMBoOXzScQrMosajPKrVVyCo0pn9sohoqIK11+5rDnKjcJ1ZvlEd8hv4Cg5RfQ89Y5fWMyTYk046uHB+jrJ4Clf3n/inZL+h8eh55IyxBOFDmNOBn3qBMIW2WX+siJ2uScCPf2BQQrpVt3GtnKA/dAz4cSfYWPcwVw3vnPC99Rxj4sI9tC0r0kSEXGWpJruUUk3lZvHaFDYoqbZywoDNlAgCMB0149MGa/M9l/5YICIJB3q6UQwHDBNoXJFp7AG0T9f2XOQQ8nEbJvs39F4uSWaFLwdd2W4alJjXpe8ABUO/HofedvPlrrJHOgQNx/zYZj9ZK5y0skJsikaRBBQM=
before_install:
- npm install jspm
- ./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
before_script:
- gulp build
- gulp clean
- gulp build --env test
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run forever-start-dist || true'
script:
- npm test
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run test-e2e || true'
